### ISSUE TITLE
CSV files with comments

### ISSUE THREAD

**Issue by enricribas** [BrewhouseTeam/csv-importer#29]
Some of our users have decided to include "comments" at the top of the CSV files. I know, this sucks, and not allowed in CSV, but... is there any way we can exclude some lines, ideally I'd like to run some lambda to check if the line should be processed. Is this possible?

Thanks, I get this isn't really your fault and this would be invalid CSV but ... users.. :)

**Comment by enricribas** [comment]
Added a PR if you'd like to get comment lines removed. 
https://github.com/BrewhouseTeam/csv-importer/pull/31

**Comment by pcreux** [comment]
As said in #31, I advise you to filter out the comments before passing the csv content down to `CsvImporter`.

Thanks for bringing that up! :)
