### ISSUE TITLE
Error on importing with missing required field

### ISSUE THREAD

**Issue by enricribas** [BrewhouseTeam/csv-importer#30]
```
6:  column :email, to: ->(email) { email.downcase }, required: true
```

When I run an import with a CSV , I get an error ...

```
NoMethodError: undefined method `downcase' for nil:NilClass
on line 6:
```

I would expect this line in the CSV to simply be skipped because it is required? I could guard against the exception but then it would create a record with a blank email. 

Thanks..

UPDATE: Not raising an error works and doesn't create the record. Not ideal, I think the block shouldn't be run unless email is present but it's an acceptable workaround

```
6:  column :email, to: ->(email) { email && email.downcase }, required: true
```

**Comment by pcreux** [comment]
That's correct, email can be nil. I believe the block should run even if email is blank so that you can do something like:

```ruby
column :email, to: ->(email) { email || "N/A" }
```

An alternative would be to make CSVImporter return an empty string instead of `nil`. See #33
