### ISSUE TITLE
How can I handle special characters like á, ü, ñ etc...

### ISSUE THREAD

**Issue by fabianrios** [BrewhouseTeam/csv-importer#35]

**Comment by pcreux** [comment]
Do you mean converting accented characters to non-accented ones? `á => a` ?

**Comment by pcreux** [comment]
Closing for now to keep things tidy. :smile_cat: 

@fabianrios Feel free to reopen with more informations.

**Comment by fabianrios** [comment]
every time I tried to import a string with special characters it just delete it like if I tried to import "Fabián" it's going to put "Fabin" in the database so, how can I make it to actually import this special characters?

**Comment by pcreux** [comment]
Can you double check that this issue comes from `CSVImporter` and not ActiveRecord or your database setup?

Does something like that work:
```ruby
u = User.create!(name: "Fabián")
u.reload
u.name
# => "Fabián" ?
```
