### ISSUE TITLE
Pass identifier in with params

### ISSUE THREAD

**Issue by agustaf9** [BrewhouseTeam/csv-importer#37]
Is there a way I could pass an identifier to csv-importer so that a user could choose the identifer(s)?

**Comment by pcreux** [comment]
Sure thing. Say you're importing tasks for a project.

```ruby
class ImportTasksCsv
  include CsvImporter

  model Task
  column :title
end

project = Project.find(params[:project_id])

ImportTasksCsv.new(file: my_file) do
  model project.tasks
end 
```

**Comment by agustaf9** [comment]
I was thinking of something more like:

`identified_by = params[:identified_by]`

Where the user would choose (with some radio buttons) between id, email and last name.

The question I have is how would I get that choice to:

    class ImportTasksCsv
      include CsvImporter

      model Task
      column :title
      identifier :identified_by
    end

**Comment by pcreux** [comment]
```ruby
class ImportTasksCsv
  include CsvImporter

  model Task
  column :title
  identifier :email #default
end

# In your controller
identified_by = params[:identified_by]
ImportTasksCsv.new(file: my_file) do
  identifier identified_by
end 
```

**Comment by pcreux** [comment]
Let me know how it goes. :)

**Comment by agustaf9** [comment]
That worked perfect! I appreciate you help.
