### ISSUE TITLE
Combine multiple columns into one

### ISSUE THREAD

**Issue by Q-u-y** [BrewhouseTeam/csv-importer#40]
Is it possible to combine several columns from the csv file into one model column? For example, I have: Vendor Name, Vendor Phone, Vendor Email, etc ... and want to merge into just one column Vendor, separate each by new lines instead.

**Comment by pcreux** [comment]
Hey @Q-u-y,

I didn't see your message, sorry about that.

You could definitely achieve this that way:

```ruby
class ImportProductCSV
  include CSVImporter

  model Product # an active record like model

  column :name
  column :vendor_name, to: ->(name, product) { product.vendor = name }
  column :vendor_phone, to: ->(phone, product) { product.vendor << "\n#{phone}" }
  column :vendor_email, to: ->(email, product) { product.vendor << "\n#{email}" }
end
```

Have a great week-end!
