### ISSUE TITLE
not able to read Japanese and Chinese content

### ISSUE THREAD

**Issue by ImJayQiu** [BrewhouseTeam/csv-importer#42]
If the csv file contents Japanese or Chinese, then will return nil.

**Comment by pcreux** [comment]
Would this help?

https://github.com/BrewhouseTeam/csv-importer#custom-encoding

**Comment by ImJayQiu** [comment]
thank you pcreux, it works only when (content: xxxxx) but (file: xxxxx), my solution is to get the contents by using CSV.read first

**Comment by pcreux** [comment]
When you provide `file: xxx`, we just set the `content` to `file.read`. `content` is then encoded in UTF-8 by default or with the encoding passed in. I'm surprised that it works when passing `content` in but not `file`.

Do you pass a specific option to `CSV.read`?

**Comment by ImJayQiu** [comment]
Hi, I am sorry I am using File.read, not CSV.read
and yes , I add encoding option in File.read

example:

csv_file = params[:file]
@csv_content = File.read(csv_file.tempfile.to_path.to_s, encoding: "UTF-8")
import = ImportModel.new(content: @csv_content)
import.run!

**Comment by pcreux** [comment]
Great! Ok, so we'll have to pass the encoding option to `File.read` as well. Feel free to create a pull-request for this if you have some time. :)

**Comment by pcreux** [comment]
PR #46
