### ISSUE TITLE
when_invalid :abort only report the first invalid record

### ISSUE THREAD

**Issue by ImJayQiu** [BrewhouseTeam/csv-importer#43]
so, how to make it report all invalid records, thanks

**Comment by pcreux** [comment]
Hey @ImJayQiu ,

You could use `when_invalid :skip` (which is the default behaviour) to report every single invalid record. It would however import all the valid records. If you'd like the import to be an all or nothing, you could wrap it in a transaction and raise an error if it failed to import some records.

```ruby
User.transaction do
  import.run!
  raise ActiveRecord::Rollback unless import.success?
end
```

**Comment by ImJayQiu** [comment]
Hi, yes, thank you very much, this is what I am looking for !
